WIDTH, HEIGHT = 120, 120 # 576, 856
SQUARE_SIZE = 8

ROWS, COLS = HEIGHT//SQUARE_SIZE, WIDTH//SQUARE_SIZE

RED = "RED"
GREEN = "GREEN"
BLUE = "BLUE"

BLACK = "BLACK"
WHITE = "WHITE"

RADIUS = int(SQUARE_SIZE/2)
CENTER_POSITION = RADIUS