WIDTH, HEIGHT = 600, 600
ROWS, COLS = WIDTH//8, HEIGHT//8

SQUARE_SIZE = WIDTH // COLS

RED = "RED"
GREEN = "GREEN"
BLUE = "BLUE"

BLACK = "BLACK"
WHITE = "WHITE"

RADIUS = int(SQUARE_SIZE/2)
CENTER_POSITION = RADIUS